import { Component, inject } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';
import { CartService } from '../../../core/services/cart.service';
@Component({selector:'app-navbar',standalone:true,imports:[RouterLink,RouterLinkActive],template:`
<header class="nav"><div class="nav__inner">
<a routerLink="/products" class="brand"><span class="brand__mark">C</span><span>Commerce</span></a>
<nav><a routerLink="/products" routerLinkActive="active" [routerLinkActiveOptions]="{exact:true}">Productos</a>@if(auth.isAdmin()){<a routerLink="/products/manage" routerLinkActive="active">Administrar</a><a routerLink="/promotions" routerLinkActive="active">Promociones</a>}</nav>
@if(auth.isLoggedIn()){<button type="button" (click)="logout()" class="cart">Salir</button>}@else{<a routerLink="/login" class="cart">Ingresar</a>}<a routerLink="/cart" class="cart"><span class="cart__icon">🛒</span><span>Carrito</span>@if(cartService.itemCount()>0){<b data-testid="cart-badge">{{cartService.itemCount()}}</b>}</a>
</div></header>`,styles:`
.nav{position:sticky;top:0;z-index:50;background:rgba(255,255,255,.94);backdrop-filter:blur(14px);border-bottom:1px solid #e8ebf2}.nav__inner{height:72px;max-width:1240px;margin:auto;padding:0 1.5rem;display:flex;align-items:center;gap:2.2rem}.brand{display:flex;align-items:center;gap:.7rem;text-decoration:none;font-size:1.12rem;font-weight:800;color:#172033}.brand__mark{width:38px;height:38px;display:grid;place-items:center;border-radius:12px;background:linear-gradient(135deg,#3157d5,#0ea5e9);color:#fff;box-shadow:0 8px 18px rgba(49,87,213,.25)}nav{display:flex;gap:.25rem;flex:1}nav a{padding:.65rem .9rem;text-decoration:none;color:#64748b;font-size:.92rem;font-weight:600;border-radius:10px}nav a:hover,nav a.active{color:#3157d5;background:#eef2ff}.cart{position:relative;text-decoration:none;display:flex;align-items:center;gap:.5rem;color:#334155;font-weight:700;padding:.65rem .85rem;border-radius:12px;background:#f8fafc}.cart b{background:#3157d5;color:#fff;border-radius:999px;min-width:20px;height:20px;display:grid;place-items:center;font-size:.7rem}@media(max-width:640px){.nav__inner{padding:0 1rem;gap:.6rem}.brand span:last-child{display:none}nav{gap:0}nav a{padding:.55rem}.cart span:not(.cart__icon){display:none}}`})
export class NavbarComponent{readonly cartService=inject(CartService);readonly auth=inject(AuthService);logout(){this.auth.logout();this.cartService.clearLocalState()}}
