-- Separate credentials from the challenge's customer records.
CREATE TABLE auth_accounts (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
 email VARCHAR(255) NOT NULL UNIQUE,
 password_hash VARCHAR(100) NOT NULL,
 role VARCHAR(20) NOT NULL CHECK (role IN ('USER', 'ADMIN'))
);
CREATE INDEX idx_auth_accounts_email ON auth_accounts(email);
