CREATE TABLE promotions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code VARCHAR(40) NOT NULL UNIQUE,
 discount_type VARCHAR(12) NOT NULL CHECK (discount_type IN ('PERCENT','FIXED')),
 amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
 starts_at TIMESTAMPTZ NOT NULL,
 ends_at TIMESTAMPTZ NOT NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMPTZ NOT NULL,
 updated_at TIMESTAMPTZ NOT NULL,
 CONSTRAINT ck_promotion_dates CHECK (ends_at > starts_at),
 CONSTRAINT ck_promotion_percent CHECK (discount_type <> 'PERCENT' OR amount <= 100)
);
ALTER TABLE carts ADD COLUMN promotion_id BIGINT REFERENCES promotions(id);
